### Something here

In [ ]:
# Write some codes, build a model

In [1]:
# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Getting the cars data
df = pd.read_csv("../data/Cars.csv")
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0

In [3]:
# Get info about dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   str
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   str
 5   seller_type    8128 non-null   str
 6   transmission   8128 non-null   str
 7   owner          8128 non-null   str
 8   mileage        7907 non-null   str
 9   engine         7907 non-null   str
 10  max_power      7913 non-null   str
 11  torque         7906 non-null   str
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), str(9)
memory usage: 825.6 KB

In [7]:
# See numerical data
df.describe()

              year  selling_price     km_driven        seats
count  8128.000000   8.128000e+03  8.128000e+03  7907.000000
mean   2013.804011   6.382718e+05  6.981951e+04     5.416719
std       4.044249   8.062534e+05  5.655055e+04     0.959588
min    1983.000000   2.999900e+04  1.000000e+00     2.000000
25%    2011.000000   2.549990e+05  3.500000e+04     5.000000
50%    2015.000000   4.500000e+05  6.000000e+04     5.000000
75%    2017.000000   6.750000e+05  9.800000e+04     5.000000
max    2020.000000   1.000000e+07  2.360457e+06    14.000000

In [8]:
# See categorical(string) data, which may also include some numerical ones
df.describe(include='str')

,name,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque
count,8128,8128,8128,8128,8128,7907,7907,7913,7906
unique,2058,4,3,2,5,393,121,322,441
top,Maruti Swift Dzire VDI,Diesel,Individual,Manual,First Owner,18.9 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm
freq,129,4402,6766,7078,5289,225,1017,377,530

In [9]:
# Check nulls
df.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [ ]:
# I should remove the null values now but I want to try the mapping first and see what happens.
# I will deal with null values after the mapping.

### Data Cleaning

In [10]:
# Looking the "owner" feature
df["owner"].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [ ]:
# As per instruction, we will map owner types to numerical values.
owner_mapping = {
    "First Owner": 1,
    "Second Owner": 2,
    "Third Owner": 3,
    "Fourth & Above Owner": 4,
    "Test Drive Car": 5
}
df["owner"] = df["owner"].map(owner_mapping)
df["owner"].value_counts()

owner
1    5289
2    2105
3     555
4     174
5       5
Name: count, dtype: int64

In [12]:
# Looking the "fuel" feature
df["fuel"].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [13]:
# As per instruction, we will remove CNG and LPG rows
df = df[~df["fuel"].isin(["CNG", "LPG"])].copy()
df["fuel"].value_counts()

fuel
Diesel    4402
Petrol    3631
Name: count, dtype: int64

In [15]:
# Looking the "milage" feature, extracts everything after the last space (the unit) and counts them
df["mileage"].str.extract(r'(\s\w+)$')[0].value_counts()

0
kmpl    7819
Name: count, dtype: int64

In [16]:
# Now we made sure they are all "kmpl", we remove the unit 
df["mileage"] = (
    df["mileage"]
    .str.split()
    .str[0]
    .astype(float)
)
df["mileage"].head(10)

0     23.40
1     21.14
2     17.70
3     23.00
4     16.10
5     20.14
7     16.10
8     23.59
9     20.00
10    19.01
Name: mileage, dtype: float64

In [17]:
# Looking the "engine" feature, extracts everything after the last space (the unit) and counts them
df["engine"].str.extract(r'(\s\w+)$')[0].value_counts()

0
CC    7819
Name: count, dtype: int64

In [18]:
# Now we made sure they are all "CC", we remove the unit 
df["engine"] = (
    df["engine"]
    .str.split()
    .str[0]
    .astype(float)
)
df["engine"].head(10)

0     1248.0
1     1498.0
2     1497.0
3     1396.0
4     1298.0
5     1197.0
7      796.0
8     1364.0
9     1399.0
10    1461.0
Name: engine, dtype: float64

In [19]:
# Looking the "max_power" feature, extracts everything after the last space (the unit) and counts them
df["max_power"].str.extract(r'(\s\w+)$')[0].value_counts()

0
bhp    7819
Name: count, dtype: int64

In [21]:
# Now we made sure they are all "bhp", we remove the unit 
df["max_power"] = (
    df["max_power"]
    .str.split()
    .str[0]
    .astype(float)
)
df["max_power"].head(10)

0      74.00
1     103.52
2      78.00
3      90.00
4      88.20
5      81.86
7      37.00
8      67.10
9      68.10
10    108.45
Name: max_power, dtype: float64

In [22]:
df.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          214
engine           214
max_power        208
torque           214
seats            214
dtype: int64

In [ ]:
# Columns with null values
null_cols = ["mileage", "engine", "max_power", "torque", "seats"]

# Filter rows where we found null values
null_rows_df = df[df[null_cols].isnull().any(axis=1)]

# View the rows
print(f"Total rows with at least one null: {len(null_rows_df)}")
null_rows_df[null_cols].head(10)

Total rows with at least one null: 214

     mileage  engine  max_power torque  seats
13       NaN     NaN        NaN    NaN    NaN
31       NaN     NaN        NaN    NaN    NaN
78       NaN     NaN        NaN    NaN    NaN
87       NaN     NaN        NaN    NaN    NaN
119      NaN     NaN        NaN    NaN    NaN
138      NaN     NaN        NaN    NaN    NaN
200      NaN     NaN        NaN    NaN    NaN
206      NaN     NaN        NaN    NaN    NaN
228      NaN     NaN        NaN    NaN    NaN
252      NaN     NaN        NaN    NaN    NaN

In [25]:
# Okay as we saw that all those null values are happening in same rows, 
# I will just drop those rows.
df = df.dropna(subset=null_cols)
print(df.isnull().sum())

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
mileage          0
engine           0
max_power        0
torque           0
seats            0
dtype: int64

In [ ]:
# As per instruction, we will only take the first word for "name" feature
# The instruction said "brand" but I won't change the name if it is okay
df["name"] = df["name"].str.split().str[0]
df.head(10)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti,2014,450000,145500,Diesel,Individual,Manual,1,23.40,1248.0,74.00,190Nm@ 2000rpm,5.0
1,Skoda,2014,370000,120000,Diesel,Individual,Manual,2,21.14,1498.0,103.52,250Nm@ 1500-2500rpm,5.0
2,Honda,2006,158000,140000,Petrol,Individual,Manual,3,17.70,1497.0,78.00,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai,2010,225000,127000,Diesel,Individual,Manual,1,23.00,1396.0,90.00,22.4 kgm at 1750-2750rpm,5.0
4,Maruti,2007,130000,120000,Petrol,Individual,Manual,1,16.10,1298.0,88.20,"11.5@ 4,500(kgm@ rpm)",5.0
5,Hyundai,2017,440000,45000,Petrol,Individual,Manual,1,20.14,1197.0,81.86,113.75nm@ 4000rpm,5.0
7,Maruti,2001,45000,5000,Petrol,Individual,Manual,2,16.10,796.0,37.00,59Nm@ 2500rpm,4.0
8,Toyota,2011,350000,90000,Diesel,Individual,Manual,1,23.59,1364.0,67.10,170Nm@ 1800-2400rpm,5.0
9,Ford,2013,200000,169000,Diesel,Individual,Manual,1,20.00,1399.0,68.10,160Nm@ 2000rpm,5.0
10,Renault,2014,500000,68000,Diesel,Individual,Manual,2,19.01,1461.0,108.45,248Nm@ 2250rpm,5.0

In [27]:
# As per instruction, drop "torque" feature
df = df.drop(columns=["torque"])
df.head(10)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,Maruti,2014,450000,145500,Diesel,Individual,Manual,1,23.40,1248.0,74.00,5.0
1,Skoda,2014,370000,120000,Diesel,Individual,Manual,2,21.14,1498.0,103.52,5.0
2,Honda,2006,158000,140000,Petrol,Individual,Manual,3,17.70,1497.0,78.00,5.0
3,Hyundai,2010,225000,127000,Diesel,Individual,Manual,1,23.00,1396.0,90.00,5.0
4,Maruti,2007,130000,120000,Petrol,Individual,Manual,1,16.10,1298.0,88.20,5.0
5,Hyundai,2017,440000,45000,Petrol,Individual,Manual,1,20.14,1197.0,81.86,5.0
7,Maruti,2001,45000,5000,Petrol,Individual,Manual,2,16.10,796.0,37.00,4.0
8,Toyota,2011,350000,90000,Diesel,Individual,Manual,1,23.59,1364.0,67.10,5.0
9,Ford,2013,200000,169000,Diesel,Individual,Manual,1,20.00,1399.0,68.10,5.0
10,Renault,2014,500000,68000,Diesel,Individual,Manual,2,19.01,1461.0,108.45,5.0

In [37]:
# Finding out about "Test Drive Cars", we already did the mapping so it is 5
test_cars = df[df['owner'] == 5]
test_cars

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
4383,Volkswagen,2019,1350000,5400,Diesel,Dealer,Manual,5,22.27,1498.0,108.60,5.0
4950,Audi,2019,6223000,7800,Petrol,Dealer,Automatic,5,15.26,1798.0,187.74,5.0
4951,Audi,2019,5923000,11500,Petrol,Dealer,Automatic,5,15.26,1798.0,187.74,5.0
4952,Audi,2019,6523000,23600,Petrol,Dealer,Automatic,5,15.26,1798.0,187.74,5.0
6220,Honda,2019,2000000,24857,Petrol,Dealer,Automatic,5,16.50,1799.0,139.46,5.0

In [38]:
# As per instructions, we will drop "Test Drive Car" which is 5
before = len(df)
df = df[df["owner"] != 5].copy()
print(f"Dropped: {len(df) - before} rows")

Dropped: -5 rows

In [ ]:
# As per instruction, we will log(selling price)
# Normally, it is safer to use log1p, now we already check null values
# So we will just use np.log()
# df["selling_price"] = np.log(df["selling_price"])
# Before that, we should see the graphs first

owner
1    5165
2    1988
3     503
4     158
5       5
Name: count, dtype: int64

### Summary here
Task 2. Report - In the end of the notebook, please write a 2-3 paragraphs summary deeply discussing and analysing the results. 
Possible points of discussion:
- Which features are important? Which are not? Why?
- Which algorithm performs well? Which does not? Why?

In [ ]:
### Write webpage for public use. Deploy.